delimiter: ;
csv-file: /raw_data-20160416T1130.csv

spring:

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  shell:
    interactive:
      enabled: false
    command:
      history:
        enabled: false