server:
  port : 8090

spring:
  main:
    banner-mode: "off"
  data:
    mongodb:
      database: library

validate-service:
  url: http://findbook.ru/search/d1
  enabled: false

management:
  endpoint:
    health:
      show-details: "ALWAYS"
    heapdump:
      enabled: false
    threaddump:
      enabled: false
    conditions:
      enabled: false
    caches:
      enabled: false
    beans:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: '@project.artifactId@'
    description: '@project.description@'
    version: '@project.version@'


logging:
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss} %-5level : %msg%n'
    file: '%d{dd-MM-yyyy HH:mm:ss} %-5level [%thread] - %msg%n'
  file: 'logs/@project.artifactId@.log'
